/*
 * Make public.store_settings authoritative for final order delivery values.
 *
 * The browser may preview delivery totals, but this trigger guarantees that
 * the database stores the configured delivery fee, free-delivery threshold,
 * delivery country and order prefix.
 */

CREATE OR REPLACE FUNCTION public.apply_store_settings_to_order()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  settings_row record;
  effective_subtotal numeric(12,2);
  configured_delivery_fee numeric(12,2) := 0;
  configured_free_threshold numeric(12,2) := 0;
  configured_country text := 'Lebanon';
  configured_prefix text := 'STER';
BEGIN
  SELECT
    delivery_fee,
    free_delivery_threshold,
    delivery_country,
    order_prefix
  INTO settings_row
  FROM public.store_settings
  WHERE id = 'default'
  LIMIT 1;

  IF FOUND THEN
    configured_delivery_fee :=
      greatest(0, coalesce(settings_row.delivery_fee, 0));

    configured_free_threshold :=
      greatest(0, coalesce(settings_row.free_delivery_threshold, 0));

    configured_country :=
      coalesce(nullif(trim(settings_row.delivery_country), ''), 'Lebanon');

    configured_prefix :=
      upper(
        coalesce(
          nullif(trim(settings_row.order_prefix), ''),
          'STER'
        )
      );
  END IF;

  effective_subtotal :=
    greatest(
      0,
      coalesce(NEW.subtotal, 0) -
      coalesce(NEW.discount_amount, 0)
    );

  IF effective_subtotal >= configured_free_threshold THEN
    NEW.delivery_fee := 0;
  ELSE
    NEW.delivery_fee := configured_delivery_fee;
  END IF;

  NEW.total :=
    effective_subtotal +
    NEW.delivery_fee;

  NEW.delivery_country :=
    configured_country;

  /*
   * Replace the legacy hard-coded STER prefix generated by place_order().
   */
  NEW.order_number :=
    configured_prefix ||
    '-' ||
    to_char(now(), 'YYYYMMDD') ||
    '-' ||
    upper(
      substr(
        replace(gen_random_uuid()::text, '-', ''),
        1,
        8
      )
    );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS
  apply_store_settings_to_order_trigger
ON public.orders;

CREATE TRIGGER
  apply_store_settings_to_order_trigger
BEFORE INSERT
ON public.orders
FOR EACH ROW
EXECUTE FUNCTION public.apply_store_settings_to_order();
